/*
--------------------------------------------------------------------------------

	Copyright (C) 2025 Graphics Park
	Apache License 2.0

    Pass: Prepare

    Reference:[1]Guillaume Abadie, 2018, A Life of a bokeh, https://epicgames.ent.box.com/s/s86j70iamxvsuu6j35pilypficznec04
              [2]Michael Potmesil & Indranil Chakravarty, 1981, Synthetic lmage Generation with a Lens and Aperture Camera Mode, https://ftp.bioeng.auckland.ac.nz/pub/pub/jtur044/references/virtual%20environments/p85-potmesil.pdf
              [3]Jorge Jimenez, 2014, Next Generation Post Processing in Call of Duty Advanced Warfare, https://www.iryoku.com/next-generation-post-processing-in-call-of-duty-advanced-warfare/
              [4]John L. Smith, 1996, Implementing Median Filters in XC4000E FPGAS

    Thank Yongxin Mo for optimizing and modifying the code.

--------------------------------------------------------------------------------
*/

#define DOF_TILE_SIZE 8
layout (local_size_x = 16, local_size_y = 16) in;

//======// Image //===============================================================================//

// Output: R: G:backgroundFactor B:foregroundFactor
layout (r11f_g11f_b10f) restrict uniform image2D presortImage;
// Output: prefiltered scene RGB
layout (r11f_g11f_b10f) restrict uniform image2D prefilterImage;

// Input: R:minDepth G:maxCOC B:minCOC A:originalCOC
layout (rgba16f) restrict uniform image2D tileDataImage;
// Input: R:neighborhoodMinDepth G:neighborhoodMaxCOC B:neighborhoodMinCOC
layout (r11f_g11f_b10f) restrict uniform image2D tileDataNeighborhoodImage;
//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"
#include "/lib/universal/Uniform.glsl"
#include "/lib/universal/Transform.glsl"
#include "/lib/universal/Random.glsl"

#include "/program/post/dof/DepthOfFieldCommon.glsl"

//======// Uniform //=============================================================================//

//uniform float centerDepthSmooth;
uniform sampler2D setup;

//======// Function //============================================================================//

//======// Main //================================================================================//

void main()
{
    ivec2 texel = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = texelToUv(texel) * 2.0f;

    // Presort
    float depth = ScreenToViewDepth(textureLod(depthtex1, uv, 0.0f).x);
    float minDepth = ScreenToViewDepth(imageLoad(tileDataImage, texel >> 1).x);
    vec2 depthCmp = DepthCmp2(depth, minDepth);
    float alpha = SampleAlpha(imageLoad(tileDataImage, texel >> 1).w);

    float backgroundFactor = depthCmp.x * alpha;

    // Prefilter
    vec3 prefilteredColor = vec3(0.0f);

    //vec2 maxMinCOC = imageLoad(tileDataNeighborhoodImage, texel >> 1).yz;
    float originalCOC = imageLoad(tileDataImage, texel >> 1).w;

    if (backgroundFactor < 1.0f)
    {
            vec3 weightedColor = vec3(0.0f);
            float totalWeight = 0.0f;
            vec2 ringScale = originalCOC * viewPixelSize * 0.16667f;// rcp(6)

            // Completely unroll
            {
				vec3 color0 = texture(setup, uv + ringScale * circularFilterOffsets[0]).rgb;
				vec3 color1 = texture(setup, uv + ringScale * circularFilterOffsets[1]).rgb;
				vec3 color2 = texture(setup, uv + ringScale * circularFilterOffsets[2]).rgb;
				vec3 color3 = texture(setup, uv + ringScale * circularFilterOffsets[3]).rgb;
				vec3 color4 = texture(setup, uv + ringScale * circularFilterOffsets[4]).rgb;
				vec3 color5 = texture(setup, uv + ringScale * circularFilterOffsets[5]).rgb;
				vec3 color6 = texture(setup, uv + ringScale * circularFilterOffsets[6]).rgb;
				vec3 color7 = texture(setup, uv + ringScale * circularFilterOffsets[7]).rgb;
				vec3 color8 = texture(setup, uv + ringScale * circularFilterOffsets[8]).rgb;

                float weight0 = KarisAverage(color0) * 1.0f;
                float weight1 = KarisAverage(color1) * 2.0f;
                float weight2 = KarisAverage(color2) * 1.0f;
                float weight3 = KarisAverage(color3) * 2.0f;
                float weight4 = KarisAverage(color4) * 4.0f;
                float weight5 = KarisAverage(color5) * 2.0f;
                float weight6 = KarisAverage(color6) * 1.0f;
                float weight7 = KarisAverage(color7) * 2.0f;
                float weight8 = KarisAverage(color8) * 1.0f;

                weightedColor += color0 * weight0 + color1 * weight1;
                weightedColor += color2 * weight2 + color3 * weight3;
                weightedColor += color4 * weight4 + color5 * weight5;
                weightedColor += color6 * weight6 + color7 * weight7;
                weightedColor += color8 * weight8;

                totalWeight += (weight0 + weight1) + (weight2 + weight3);
                totalWeight += (weight4 + weight5) + (weight6 + weight7);
                totalWeight += weight8;
            }
            prefilteredColor = weightedColor / totalWeight;
	}

    imageStore(prefilterImage, texel, vec4(prefilteredColor, 0.0f));

}
