/*
--------------------------------------------------------------------------------

	Copyright (C) 2025 Graphics Park
	Apache License 2.0

    Pass: Median Filter

    Reference:[1]Guillaume Abadie, 2018, A Life of a bokeh, https://epicgames.ent.box.com/s/s86j70iamxvsuu6j35pilypficznec04
              [2]Michael Potmesil & Indranil Chakravarty, 1981, Synthetic lmage Generation with a Lens and Aperture Camera Mode, https://ftp.bioeng.auckland.ac.nz/pub/pub/jtur044/references/virtual%20environments/p85-potmesil.pdf
              [3]Jorge Jimenez, 2014, Next Generation Post Processing in Call of Duty Advanced Warfare, https://www.iryoku.com/next-generation-post-processing-in-call-of-duty-advanced-warfare/
              [4]John L. Smith, 1996, Implementing Median Filters in XC4000E FPGAS

    Thank Yongxin Mo for optimizing and modifying the code.

--------------------------------------------------------------------------------
*/

#define DOF_TILE_SIZE 8
layout (local_size_x = 16, local_size_y = 16) in;

//======// Image //===============================================================================//

// Input: RGB:color
layout (r11f_g11f_b10f) restrict uniform image2D mainDataImage;
// Input: RGB:color A:depth
layout (rgba16f) restrict uniform image2D setupImage;

// Output: RGB:color A:alpha
layout (rgba16f) restrict uniform image2D colorimg0;

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"
#include "/lib/universal/Uniform.glsl"
#include "/lib/universal/Transform.glsl"
#include "/lib/universal/Random.glsl"

#include "/program/post/dof/DepthOfFieldCommon.glsl"

//======// Uniform //=============================================================================//

// uniform float centerDepthSmooth;
uniform sampler2D mainData;
uniform sampler2D prefilter;
uniform sampler2D setup;
uniform sampler2D coc;
//======// Function //============================================================================//

//======// Main //================================================================================//

void main()
{
    ivec2 texel = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = texelToUv(texel);

    vec2 halfResPos = vec2(texel) * 0.5f;
    ivec2 halfResBase = ivec2(floor(halfResPos));
    vec2 weight = smoothstep(0.0, 1.0, fract(halfResPos));

	// Hybrid median-bilinear filter
    vec3 samples[4];
    for(uint i = 0; i < 4; i++) {
        ivec2 offset = ivec2(i & 1, i >> 1);
        ivec2 halfTexel = halfResBase + offset;

        vec3 medianColor = MedianFilter3x3(mainData, halfTexel);
        samples[i] = medianColor;
    }

    vec3 s0 = mix(samples[0], samples[1], weight.x);
    vec3 s1 = mix(samples[2], samples[3], weight.x);
    vec3 filtered = mix(s0, s1, weight.y);

    vec3 originalImage = texture(setup, uv).rgb;

    vec3 mixedImage = mix(originalImage, filtered, saturate(texelFetch(coc, texel / 2, 0).x));

    imageStore(colorimg0, texel, vec4(mixedImage, 0.0f));
}
