/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2024 HaringPro
	Apache License 2.0

	Pass: Downsample bloom tiles

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

#define BLOOM_BLUR_SAMPLES 1 // [1 2 3 4 5 6 7 8]

//======// Uniform //=============================================================================//

writeonly uniform image2D colorimg4;

uniform sampler2D colortex1; // TAA image output
uniform sampler2D colortex4; // Bloom tile input

uniform vec2 viewSize;
uniform vec2 viewPixelSize;

//======// Function //============================================================================//

#if DOWNSAMPLE_LEVEL == 0
	#define bloomTileTex colortex1
#else
	#define bloomTileTex colortex4
#endif
#define loadTile(uv) textureLod(bloomTileTex, uv, 0.0).rgb

const vec2 bloomTileOffset[7] = vec2[7](
	vec2(0.0000, 0.0000),
	vec2(0.0000, 0.5000),
	vec2(0.2500, 0.5000),
	vec2(0.2500, 0.6250),
	vec2(0.3125, 0.6250),
	vec2(0.3125, 0.6563),
	vec2(0.3281, 0.6563)
);

vec3 CalculateBloomTile(in vec2 uv) {
	vec3  bloomTile = vec3(0.0);
	float sumWeight = EPS;

	for (int y = -BLOOM_BLUR_SAMPLES; y <= BLOOM_BLUR_SAMPLES; ++y) {
		for (int x = -BLOOM_BLUR_SAMPLES; x <= BLOOM_BLUR_SAMPLES; ++x) {
			vec3 sampleTile = loadTile(uv + vec2(x, y) * viewPixelSize);
			float weight = saturate(1.0 - sdot(vec2(x, y)) * 0.25);

			#if DOWNSAMPLE_LEVEL == 0
				weight *= karisAverage(sampleTile);
			#endif

			bloomTile += sampleTile * weight;
			sumWeight += weight;
		}
	}

	return bloomTile * rcp(sumWeight);
}

//======// Main //================================================================================//
void main() {
    vec2 baseUv = vec2(gl_GlobalInvocationID.xy) * 2.0 + 1.0;

	const int index = max(0, DOWNSAMPLE_LEVEL - 1);
    vec2 srcUv = (baseUv + float(index * 12)) * viewPixelSize + bloomTileOffset[index];

	if (clamp(srcUv, viewPixelSize, 1.0 - viewPixelSize) == srcUv) {
		vec3 bloomTile = CalculateBloomTile(srcUv);

		vec2 dstTexel = vec2(gl_GlobalInvocationID.xy + DOWNSAMPLE_LEVEL * 12);
		dstTexel += bloomTileOffset[DOWNSAMPLE_LEVEL] * viewSize + 0.5;
		imageStore(colorimg4, ivec2(dstTexel), vec4(bloomTile, 1.0));
	}
}
