/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2024 HaringPro
	Apache License 2.0

	Pass: Compute clouds

--------------------------------------------------------------------------------
*/

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;

#ifndef CLOUD_TAAU_ENABLED
	const vec2 workGroupsRender = vec2(1.0, 1.0);
#elif CLOUD_TAAU_SCALE == 2
	const vec2 workGroupsRender = vec2(0.5, 0.5);
#elif CLOUD_TAAU_SCALE == 3
	const vec2 workGroupsRender = vec2(0.333333, 0.333333);
#elif CLOUD_TAAU_SCALE == 4
	const vec2 workGroupsRender = vec2(0.25, 0.25);
#endif

//======// Uniform //=============================================================================//

writeonly uniform image2D cloudOriginImg;
writeonly uniform image2D cloudDepthOriginImg;

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#include "/lib/universal/SSBO.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Random.glsl"

#include "/lib/atmosphere/Common.glsl"
#include "/lib/atmosphere/PrecomputedAtmosphericScattering.glsl"

#include "/lib/atmosphere/clouds/Render.glsl"

vec3 ScreenToViewVectorRaw(in vec2 screenCoord) {
	vec2 NDCCoord = screenCoord * 2.0 - 1.0;
	return normalize(vec3(diagonal2(gbufferProjectionInverse) * NDCCoord, gbufferProjectionInverse[3].z));
}

float SampleDepthMax4x4(in sampler2D depthTex, in vec2 coord) {
	// 4x4 pixel neighborhood using textureGatherOffset
	float LL = maxOf(textureGatherOffset(depthTex, coord, ivec2(-2, -2)));
	float LR = maxOf(textureGatherOffset(depthTex, coord, ivec2(-2,  2)));
	float UL = maxOf(textureGatherOffset(depthTex, coord, ivec2( 2, -2)));
	float UR = maxOf(textureGatherOffset(depthTex, coord, ivec2( 2,  2)));

	return max(max(LL, LR), max(UL, UR));
}

//======// Main //================================================================================//
void main() {
    ivec2 screenTexel = ivec2(gl_GlobalInvocationID.xy);

	#ifdef CLOUD_TAAU_ENABLED
		vec2 ditheredTexel = vec2(screenTexel) + R2(frameCounter + 11);
		ivec2 cloudTexel = ivec2(ditheredTexel * CLOUD_TAAU_SCALE);
	#else
		#define cloudTexel screenTexel
	#endif
	vec2 cloudUv = texelToUv(cloudTexel);

	vec4 cloudOut = vec4(0.0, 0.0, 0.0, 1.0);
	float cloudDepth = -1.0;

	float depthMax = SampleDepthMax4x4(depthtex2, cloudUv);

	#if defined DISTANT_HORIZONS
		if (depthMax > 1.0 - EPS) depthMax = SampleDepthMax4x4(dhDepthTex1, cloudUv);
	#endif

	if (depthMax > 1.0 - EPS) {
		vec2 noise = SampleStbnVec2(cloudTexel, frameCounter + 11);

		vec3 viewDir  = ScreenToViewVectorRaw(cloudUv);
		vec3 worldDir = mat3(gbufferModelViewInverse) * viewDir;

		cloudOut = RenderClouds(worldDir, noise, cloudDepth);

		// Crepuscular rays
		#ifdef CREPUSCULAR_RAYS
			#ifdef CLOUD_SHADOWS
			if (viewerHeight < cumulusBottomRadius) {
				vec4 crepuscularRays = RaymarchCrepuscular(worldDir, noise.x);

				cloudOut *= crepuscularRays.a;
				cloudOut.rgb += crepuscularRays.rgb;
			}
			#endif
		#endif
	}

	imageStore(cloudOriginImg, screenTexel, cloudOut);
	imageStore(cloudDepthOriginImg, screenTexel, vec4(cloudDepth));
}
