/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2024 HaringPro
	Apache License 2.0

	Pass:

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(1.0, 1.0);
const ivec3 workGroups = ivec3(1, 1, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

layout (rgba16f, location = 0) writeonly uniform image2D colorimg0; //
layout (rgba16f, location = 1) readonly uniform image2D colorimg1; //
layout (rgba16f, location = 2) restrict uniform image2D colorimg3; //

uniform sampler2D sampler0;
uniform sampler2D sampler1;
uniform sampler2D sampler2;

//======// Shared Memory //=======================================================================//

//======// Struct //==============================================================================//

//======// Function //============================================================================//

//================================================================================================//

//======// Main //================================================================================//
void main() {
	// Z-Order
	ivec2 texelPos = ivec2(gl_GlobalInvocationID.xy);

	// Quadratic
    uvec2 localPos = QuadLayout16x16(gl_LocalInvocationIndex);
    ivec2 texelPos = ivec2(localPos + gl_WorkGroupID.xy * gl_WorkGroupSize.xy);

    vec2 texCoord = texelToUv(texelPos);
	imageStore(colorimg0, texelPos, vec4(imageLoad(colorimg1, texelPos).rgb, 1.0));
}