/*
--------------------------------------------------------------------------------

	Revelation Shaders

	Copyright (C) 2024 HaringPro
	Apache License 2.0

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
const ivec3 workGroups = ivec3(16, 16, 128);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly uniform image3D baseNoiseImg;

//======// Function //============================================================================//

#define UI0 1597334673U
#define UI1 3812015801U
#define UI3 uvec3(UI0, UI1, 2798796415U)
#define UIF (1.0 / float(0xffffffffU))

vec3 Hash33(const vec3 p) {
    uvec3 q = uvec3(ivec3(p)) * UI3;
    q = (q.x ^ q.y ^ q.z) * UI3;
    return vec3(q) * UIF;
}

#define FPRIME 1317666547U
#define VPRIME uvec3(3480082861U, 2420690917U, 2149110343U)
#define SMALLESTFLOAT (1.0 / float(0xffffffffU))
float Hash13(const vec3 p) {
    const uvec3 q = uvec3(ivec3(p)) * VPRIME;
    const uint n = (q.x & q.y ^ q.z) * FPRIME;
    return float(n) * SMALLESTFLOAT;
}

/// Tileable 3D worley noise
/// Source: <https://www.shadertoy.com/view/3dVXDc>
float WorleyNoise(const vec3 uv, const float freq) {
    const vec3 id = floor(uv);
    const vec3 p = mod(uv, 1.0);

    float minDist = 10000.0;
    for (float x = -1.0; x <= 1.0; ++x) {
        for (float y = -1.0; y <= 1.0; ++y) {
            for (float z = -1.0; z <= 1.0; ++z) {
                const vec3 offset = vec3(x, y, z);
                vec3 h = (-1.0 + 2.0 * Hash33(mod(id + offset, freq.xxx))) * 0.5 + 0.5;
                h += offset;
                const vec3 d = p - h;
                minDist = min(minDist, dot(d, d));
            }
        }
    }
    return 1.0 - minDist;
}

float WorleyFbm(const vec3 p, const float freq) {
    return WorleyNoise(p * freq, freq) * .625 +
           WorleyNoise(p * freq * 2., freq * 2.) * .25 +
           WorleyNoise(p * freq * 4., freq * 4.) * .125;
}

// Simplified Smoothstep https://www.desmos.com/calculator/un0o21eokv
float SmoothValue(float x) {
    x = clamp(x, 0.0, 1.0);
    return x * x * (3.0 - 2.0 * x);
}

// Alligator Noise, originally from Side Effects:
// https://www.sidefx.com/docs/hdk/alligator_2alligator_8_c-example.html
float AlligatorNoise(vec3 p, uint gridsize, uvec3 seed) {
    // scale the position
    p *= float(gridsize);

    vec3 id = floor(p); // Integer coordinates
    vec3 grid = p - id; // Fractional coordinates

    // Initialize results
    float densest = 0.0;
    float secondDensest = 0.0;

    // compare to 3x3x3 neighbor cells
    for (int ix = -1; ix <= 1; ++ix) {
        for (int iy = -1; iy <= 1; ++iy) {
            for (int iz = -1; iz <= 1; ++iz) {
                // Offset to the neighbor cell
                vec3 offset = vec3(ix, iy, iz);

                // Current Cell coordinates
                vec3 cell = id + offset;

                // makes the noise repeat at pos 0-1
                cell = mod(cell, float(gridsize));

                // Modify the result with some Offset
                // This hash doesn't like 0 so plus 1
                cell += vec3(seed);

                // Get random center of the Cell
                vec3 center = Hash33(cell) + offset;

                // Distance from center
                float dist = distance(grid, center);

                // 'if(dist < 1.0)' doesn't have any effect and doesn't improve
                // performance. See: https://www.shadertoy.com/view/MflGWM

                // Get random density scaled by the distance to the random point
                float density = Hash13(cell) * SmoothValue(1.0 - dist);

                // find largest values
                if (densest < density) {
                    // move previous highest to second place
                    secondDensest = densest;
                    // update highest to current height
                    densest = density;
                } else if (secondDensest < density) {
                    // update second highest to current height
                    secondDensest = density;
                }
            }
        }
    }
    // Subtract two largest density values for the result
    return densest - secondDensest;
}

float AlligatorFbm(const vec3 p, float gridsize, const uint octaves, const float lacunarity, const float persistence) {
    // Initialize the constants
    // For Amplitude math see: https://www.desmos.com/calculator/xgqeepapwn
    float amplitude = 1.0;
    float amplitudeSum = 0.0;
    float result = 0.0;
    uvec3 seed = uvec3(92364, 92364, 92364);

    for (uint i = 0u; i < octaves; ++i) {
        // sample noise and apply amplitude
        result += AlligatorNoise(p, uint(gridsize), seed) * amplitude;

        // add up amplitude to normalize result later
        amplitudeSum += amplitude;

        // increase frequency for the next octave
        gridsize *= lacunarity;

        // decrease amplitude for the next octave
        amplitude *= persistence;

        // change seed/offset noise so it is unique for the next octave
        seed += uvec3(gridsize, gridsize, gridsize);
    }

    // normalize the result to 0-1 range
    result /= amplitudeSum;

    return result;
}

//======// Main //================================================================================//
void main() {
	ivec3 tid = ivec3(gl_GlobalInvocationID.xyz);
	vec3 uv = (vec3(tid) + 0.5) / vec3(imageSize(baseNoiseImg));

    float noise = AlligatorFbm(uv, 5.0, 8, 2.0, 0.65);
    noise = pow(noise * 1.5, 0.7);

	imageStore(baseNoiseImg, tid, vec4(noise));
}