/*
=============================================================================

    TextRenderer.glsl

    Description: This is a comprehensive debug tool.
                 It includes a character renderer capable of rendering 26 English letters
                 (and even some simple Chinese characters) and displaying single-line sentences.
                 It also includes a number renderer and a function plotter that can output the values of almost all types of variables.
                 Additionally, it still has some drawbacks,
                 such as potentially causing the game to crash when outputting certain matrices.

    Reference: https://github.com/moyongxin/mc-shaders-helpers
               https://www.shadertoy.com/view/WslGzl

    Copyright © 2024 Grapics Park

    DO NOT REMOVE THE INFORMATION HEAD

=============================================================================

    How to use?
    1. Copy this file to your shaderpacks.
    2. Include this file in your fragment shader.
    3. Put your sentence in the following array.
    4. Call the function renderText().
    5. Please call functions like "outputNumber" for the mathematical output renderer.
    6. To use a mathematical function renderer, change its mathematical function expression in the original function.
    7. If you want to view all characters, please call debugCharacters().

    Encoding
    uvec3(x:lower part,y:upper part,z:vertical offset)

    It use a 8*8(4*8*2) dot matrix

    eg:A("1" indicates that the pixel belongs to the character)

    original
    0 0 0 1 1 0 0 0
    0 0 1 0 0 1 0 0
    0 0 1 0 0 1 0 0
    0 1 0 0 0 0 1 0
    0 1 1 1 1 1 1 0
    0 1 0 0 0 0 1 0
    0 1 0 0 0 0 1 0
    0 1 0 0 0 0 1 0

    upper part
    <-<-<-<-<-<-<-
    0 0 0 1 1 0 0 0 (1)
    0 0 1 0 0 1 0 0 (2)
    0 0 1 0 0 1 0 0 (3)
    0 1 0 0 0 0 1 0 (4)
    lower part
    <-<-<-<-<-<-<-
    0 1 1 1 1 1 1 0 (1)
    0 1 0 0 0 0 1 0 (2)
    0 1 0 0 0 0 1 0 (3)
    0 1 0 0 0 0 1 0 (4)

    Read it form right to left, form from top to bottom.
    upper part (1)00011000 (2)00100100 (3)00100100 (4)01000010
    lower part (1)01111110 (2)01000010 (3)01000010 (4)01000010

    Combine 0 and 1 together and convert to an unsigned 16-bit integer in hexadecimal format.
    upper part (1)00011000 (2)00100100 (3)00100100 (4)01000010 -> 0x18242442u
    lower part (1)01111110 (2)01000010 (3)01000010 (4)01000010 -> 0x7e424242u

    Place it into the xy components of a uvec3 (x is the lower half, y is the upper half).
    const uvec3 _A_ = uvec3(0x7e424242u,0x18242442u,0);

    When you need vertical offset,please change Z components of a uvec3.

    If you don't like the style of characters,you can edit it by yourself.

    If you don't understand how it works,don't edit the character code.

    It is strange that we can't use "char" as name of variable or constant on NVGPU.

    We have used some bitwise operations to accelerate:
    x << n = x * 2 ^ n      x >> n = x / 2 ^ n
=============================================================================
*/

//==============================// Character Encoding //======================================//

//----------// Generated by qwertyuiop's generator //-----------//
//|                chars                 | lower part | upper part | vertical offset |
    const uvec3 CHAR_A             = uvec3(0x11111100, 0x0E111F11, 1);
    const uvec3 CHAR_B             = uvec3(0x11110F00, 0x0F110F11, 1);
    const uvec3 CHAR_C             = uvec3(0x01110E00, 0x0E110101, 1);
    const uvec3 CHAR_D             = uvec3(0x11110F00, 0x0F111111, 1);
    const uvec3 CHAR_E             = uvec3(0x01011F00, 0x1F010701, 1);
    const uvec3 CHAR_F             = uvec3(0x01010100, 0x1F010701, 1);
    const uvec3 CHAR_G             = uvec3(0x11110E00, 0x1E011911, 1);
    const uvec3 CHAR_H             = uvec3(0x11111100, 0x11111F11, 1);
    const uvec3 CHAR_I             = uvec3(0x02020700, 0x07020202, 1);
    const uvec3 CHAR_J             = uvec3(0x10110E00, 0x10101010, 1);
    const uvec3 CHAR_K             = uvec3(0x11111100, 0x11090709, 1);
    const uvec3 CHAR_L             = uvec3(0x01011F00, 0x01010101, 1);
    const uvec3 CHAR_M             = uvec3(0x11111100, 0x111B1511, 1);
    const uvec3 CHAR_N             = uvec3(0x11111100, 0x11131519, 1);
    const uvec3 CHAR_O             = uvec3(0x11110E00, 0x0E111111, 1);
    const uvec3 CHAR_P             = uvec3(0x01010100, 0x0F110F01, 1);
    const uvec3 CHAR_Q             = uvec3(0x11091600, 0x0E111111, 1);
    const uvec3 CHAR_R             = uvec3(0x11111100, 0x0F110F11, 1);
    const uvec3 CHAR_S             = uvec3(0x10110E00, 0x1E010E10, 1);
    const uvec3 CHAR_T             = uvec3(0x04040400, 0x1F040404, 1);
    const uvec3 CHAR_U             = uvec3(0x11110E00, 0x11111111, 1);
    const uvec3 CHAR_V             = uvec3(0x0A0A0400, 0x11111111, 1);
    const uvec3 CHAR_W             = uvec3(0x151B1100, 0x11111111, 1);
    const uvec3 CHAR_X             = uvec3(0x11111100, 0x110A040A, 1);
    const uvec3 CHAR_Y             = uvec3(0x04040400, 0x110A0404, 1);
    const uvec3 CHAR_Z             = uvec3(0x02011F00, 0x1F100804, 1);

    const uvec3 CHAR_a             = uvec3(0x1E000000, 0x0E101E11, 3);
    const uvec3 CHAR_b             = uvec3(0x11110F00, 0x01010D13, 1);
    const uvec3 CHAR_c             = uvec3(0x0E000000, 0x0E110111, 3);
    const uvec3 CHAR_d             = uvec3(0x11111E00, 0x10101619, 1);
    const uvec3 CHAR_e             = uvec3(0x1E000000, 0x0E111F01, 3);
    const uvec3 CHAR_f             = uvec3(0x02020200, 0x0C020F02, 1);
    const uvec3 CHAR_g             = uvec3(0x100F0000, 0x1E11111E, 3);
    const uvec3 CHAR_h             = uvec3(0x11111100, 0x01010D13, 1);
    const uvec3 CHAR_i             = uvec3(0x01010100, 0x01000101, 1);
    const uvec3 CHAR_j             = uvec3(0x1011110E, 0x10001010, 1);
    const uvec3 CHAR_k             = uvec3(0x03050900, 0x01010905, 1);
    const uvec3 CHAR_l             = uvec3(0x01010200, 0x01010101, 1);
    const uvec3 CHAR_m             = uvec3(0x11000000, 0x0B151511, 3);
    const uvec3 CHAR_n             = uvec3(0x11000000, 0x0F111111, 3);
    const uvec3 CHAR_o             = uvec3(0x0E000000, 0x0E111111, 3);
    const uvec3 CHAR_p             = uvec3(0x01010000, 0x0D13110F, 3);
    const uvec3 CHAR_q             = uvec3(0x10100000, 0x1619111E, 3);
    const uvec3 CHAR_r             = uvec3(0x01000000, 0x0D130101, 3);
    const uvec3 CHAR_s             = uvec3(0x0F000000, 0x1E010E10, 3);
    const uvec3 CHAR_t             = uvec3(0x02040000, 0x02070202, 2);
    const uvec3 CHAR_u             = uvec3(0x1E000000, 0x11111111, 3);
    const uvec3 CHAR_v             = uvec3(0x04000000, 0x1111110A, 3);
    const uvec3 CHAR_w             = uvec3(0x1E000000, 0x11111515, 3);
    const uvec3 CHAR_x             = uvec3(0x11000000, 0x110A040A, 3);
    const uvec3 CHAR_y             = uvec3(0x100F0000, 0x1111111E, 3);
    const uvec3 CHAR_z             = uvec3(0x1F000000, 0x1F080402, 3);

    const uvec3 CHAR_0             = uvec3(0x13110E00, 0x0E111915, 1);
    const uvec3 CHAR_1             = uvec3(0x04041F00, 0x04060404, 1);
    const uvec3 CHAR_2             = uvec3(0x02011F00, 0x0E11100C, 1);
    const uvec3 CHAR_3             = uvec3(0x10110E00, 0x0E11100C, 1);
    const uvec3 CHAR_4             = uvec3(0x1F101000, 0x18141211, 1);
    const uvec3 CHAR_5             = uvec3(0x10110E00, 0x1F010F10, 1);
    const uvec3 CHAR_6             = uvec3(0x11110E00, 0x0C02010F, 1);
    const uvec3 CHAR_7             = uvec3(0x04040400, 0x1F111008, 1);
    const uvec3 CHAR_8             = uvec3(0x11110E00, 0x0E11110E, 1);
    const uvec3 CHAR_9             = uvec3(0x10080600, 0x0E11111E, 1);

    const uvec3 CHAR_UNDERSCORE    = uvec3(0x00000000, 0x1F000000, 8);// _
    const uvec3 CHAR_EXCLAMATION   = uvec3(0x01000100, 0x01010101, 1);// !
    const uvec3 CHAR_QUOTE         = uvec3(0x00000000, 0x05050000, 1);// "
    const uvec3 CHAR_DOLLAR        = uvec3(0x100F0400, 0x041E010E, 1);// $
    const uvec3 CHAR_PERCENT       = uvec3(0x02121100, 0x11090804, 1);// %
    const uvec3 CHAR_AMPERSAND     = uvec3(0x0D091600, 0x040A0416, 1);// &
    const uvec3 CHAR_APOSTROPHE    = uvec3(0x00000000, 0x01010000, 1);// '
    const uvec3 CHAR_LEFT_PAREN    = uvec3(0x01020C00, 0x0C020101, 1);// (
    const uvec3 CHAR_RIGHT_PAREN   = uvec3(0x08040300, 0x03040808, 1);// )
    const uvec3 CHAR_ASTERISK      = uvec3(0x00000000, 0x09060900, 3);// *
    const uvec3 CHAR_PLUS          = uvec3(0x04000000, 0x04041F04, 3);// +
    const uvec3 CHAR_MINUS         = uvec3(0x00000000, 0x1F000000, 5);// -
    const uvec3 CHAR_COLON         = uvec3(0x01010000, 0x01010000, 2);// :
    const uvec3 CHAR_SEMICOLON     = uvec3(0x01010100, 0x01010000, 2);// ;
    const uvec3 CHAR_LESS_THAN     = uvec3(0x02040800, 0x08040201, 1);// <
    const uvec3 CHAR_EQUAL         = uvec3(0x00000000, 0x1F00001F, 3);// =
    const uvec3 CHAR_GREATER_THAN  = uvec3(0x04020100, 0x01020408, 1);// >
    const uvec3 CHAR_QUESTION      = uvec3(0x04000400, 0x0E111008, 1);// ?
    const uvec3 CHAR_AT            = uvec3(0x3D013E00, 0x1E212D2D, 1);// @
    const uvec3 CHAR_LEFT_BRACKET  = uvec3(0x01010700, 0x07010101, 1);// [
    const uvec3 CHAR_RIGHT_BRACKET = uvec3(0x04040700, 0x07040404, 1);// ]
    const uvec3 CHAR_CARET         = uvec3(0x00000000, 0x040A1100, 1);// ^
    const uvec3 CHAR_BACKTICK      = uvec3(0x00000000, 0x02010000, 1);// `
    const uvec3 CHAR_LEFT_BRACE    = uvec3(0x02020C00, 0x0C020201, 1);// {
    const uvec3 CHAR_PIPE          = uvec3(0x01010100, 0x01010100, 1);// |
    const uvec3 CHAR_RIGHT_BRACE   = uvec3(0x04040300, 0x03040408, 1);// }
    const uvec3 CHAR_TILDE         = uvec3(0x00000000, 0x26190000, 1);// ~
    const uvec3 CHAR_COMMA         = uvec3(0x00000000, 0x01010100, 6);// ,
    const uvec3 CHAR_DOT           = uvec3(0x00000000, 0x01010000, 6);// .
    const uvec3 CHAR_SLASH         = uvec3(0x02020100, 0x10080804, 1);// /
    const uvec3 CHAR_BACKSLASH     = uvec3(0x08081000, 0x01020204, 1);// "\"
    const uvec3 CHAR_HASH          = uvec3(0x1F0A0A00, 0x0A0A1F0A, 1);// #
    const uvec3 CHAR_SPACE         = uvec3(0x00000000, 0x00000000, 8);




//==============================// Your Text //===============================================//

// Put your sentence in "text_encodings" array. Use comma to separate characters.
// You can use the "text_advances" array to control the horizontal layout.
// You can use the generator to encode your sentence(https://github.com/moyongxin/mc-shaders-helpers)
// You can render up to 3 lines of text with background.

// Original Text: Ethereal
const uvec3 text_encodings_0[] = {CHAR_E,CHAR_t,CHAR_h,CHAR_e,CHAR_r,CHAR_e,CHAR_a,CHAR_l,};
const int text_advances_0[] = {0,6,10,16,22,28,34,40,};

// Original Text: T_50
const uvec3 text_encodings_1[] = {CHAR_T,CHAR_UNDERSCORE,CHAR_5,CHAR_0,};
const int text_advances_1[] = {0,6,12,18,};

// Original Text: Minecraft.
const uvec3 text_encodings_2[] = {CHAR_M,CHAR_i,CHAR_n,CHAR_e,CHAR_c,CHAR_r,CHAR_a,CHAR_f,CHAR_t,};
const int text_advances_2[] = {0,6,8,14,20,26,32,38,43,};

//==============================// Character Render //========================================//

bool isChar(uint text, uint index) {
	return index < 32u && bool(text >> index & 1u); // Use the right shift operation to decode our character code
}

bool isText(ivec2 texel, ivec2 pos, uvec3 text, int size) {
    pos.y -= int(text.z) * size; // Vertical offset

    ivec2 relPos = (texel - pos) / size;

    // Calculate the index for the lower part
    // 8 is the number of columns in the character grid
    uint index = uint(relPos.x + (relPos.y << 3));

    // Lower part
    bool result = isChar(text.x, index);

    // Upper part
    result = result || isChar(text.y, index - 32u);

    return result;
}

//=====================================// Test Function //====================================//

const uvec3 charactersDebug[] = {
    CHAR_A,CHAR_B,CHAR_C,CHAR_D,
    CHAR_E,CHAR_F,CHAR_G,CHAR_H,
    CHAR_I,CHAR_J,CHAR_K,CHAR_L,
    CHAR_M,CHAR_N,CHAR_O,CHAR_P,
    CHAR_Q,CHAR_R,CHAR_S,CHAR_T,
    CHAR_U,CHAR_V,CHAR_W,CHAR_X,
    CHAR_Y,CHAR_Z,

    CHAR_a,CHAR_b,CHAR_c,CHAR_d,
    CHAR_e,CHAR_f,CHAR_g,CHAR_h,
    CHAR_i,CHAR_j,CHAR_k,CHAR_l,
    CHAR_m,CHAR_n,CHAR_o,CHAR_p,
    CHAR_q,CHAR_r,CHAR_s,CHAR_t,
    CHAR_u,CHAR_v,CHAR_w,CHAR_x,
    CHAR_y,CHAR_z,

    CHAR_0,CHAR_1,CHAR_2,CHAR_3,
    CHAR_4,CHAR_5,CHAR_6,CHAR_7,
    CHAR_8,CHAR_9,

    CHAR_UNDERSCORE,
    CHAR_EXCLAMATION,
    CHAR_QUOTE,
    CHAR_DOLLAR,
    CHAR_PERCENT,
    CHAR_AMPERSAND,
    CHAR_APOSTROPHE,
    CHAR_LEFT_PAREN,
    CHAR_RIGHT_PAREN,
    CHAR_ASTERISK,
    CHAR_PLUS,
    CHAR_MINUS,
    CHAR_COLON,
    CHAR_SEMICOLON,
    CHAR_LESS_THAN,
    CHAR_EQUAL,
    CHAR_GREATER_THAN,
    CHAR_QUESTION,
    CHAR_AT,
    CHAR_LEFT_BRACKET,
    CHAR_RIGHT_BRACKET,
    CHAR_CARET,
    CHAR_BACKTICK,
    CHAR_LEFT_BRACE,
    CHAR_PIPE,
    CHAR_RIGHT_BRACE,
    CHAR_TILDE,
    CHAR_COMMA,
    CHAR_DOT,
    CHAR_SLASH,
    CHAR_BACKSLASH,
    CHAR_HASH,
    CHAR_SPACE
};

vec3 debugCharacters(ivec2 pos, int size){
    vec3 result = vec3(0.0);

    ivec2 texel = ivec2(gl_FragCoord.st);
    ivec2 posOffset = ivec2(0, size);

    for (uint i = 0; i < charactersDebug.length(); i++) {
        uint line =(i / 12) % 10;
        ivec2 characterPos = pos + posOffset + ivec2(size * (i * 7 - line * 84), - line * 10 * size);

        if (max(texel, characterPos - ivec2(0, size)) == texel) {
            if (min(texel, characterPos + ivec2(size * 7, size * 11)) == texel) {
                result += vec3(1.0) * uint(isText(texel, characterPos, charactersDebug[i], size));
            }
        }
    }

    return result;
}

//=================================// Text Render //==========================================//

vec3 renderChar(ivec2 pos, int size, vec3 color, uvec3 character) {
	vec3 result = vec3(0.0);
    ivec2 screenTexel = ivec2(gl_FragCoord.st);

    if (max(screenTexel, ivec2(pos.x, pos.y - size * 6)) == screenTexel) {
        if (min(screenTexel, ivec2(pos.x + size * 6, pos.y + size * 10)) == screenTexel) {
               result = uint(isText(screenTexel, ivec2(pos.x, pos.y + size), character, size)) * color;
        }
    }

	return result;
}

vec3 renderText_0(ivec2 pos, int size, vec3 color) {
	vec3 result = vec3(0.0);
    ivec2 screenTexel = ivec2(gl_FragCoord.st);

    if (max(screenTexel, ivec2(pos.x, pos.y - size * 6)) == screenTexel) {
        int lastText = text_advances_0[text_encodings_0.length() - 1];
        if (min(screenTexel, ivec2(pos.x + size * (lastText + 6), pos.y + size * 11)) == screenTexel) {
            int relPos = screenTexel.x - pos.x;
            relPos /= size;

            // Binary search for the character index
            int left = 0, right = text_advances_0.length();
            while (left < right) {
                int middle = (left + right) >> 1;
                if (relPos >= text_advances_0[middle]) left = middle + 1;
                else right = middle;
            }

            int index = left - 1;
            pos += ivec2(size * text_advances_0[index], 0);
            result = uint(isText(screenTexel, pos, text_encodings_0[index], size)) * color;
        }
    }



	return result;
}

vec3 renderText_1(ivec2 pos, int size, vec3 color) {
	vec3 result = vec3(0.0);
    ivec2 screenTexel = ivec2(gl_FragCoord.st);

    if (max(screenTexel, ivec2(pos.x, pos.y - size * 6)) == screenTexel) {
        int lastText = text_advances_1[text_encodings_1.length() - 1];
        if (min(screenTexel, ivec2(pos.x + size * (lastText + 6), pos.y + size * 11)) == screenTexel) {
            int relPos = screenTexel.x - pos.x;
            relPos /= size;

            // Binary search for the character index
            int left = 0, right = text_advances_1.length();
            while (left < right) {
                int middle = (left + right) >> 1;
                if (relPos >= text_advances_1[middle]) left = middle + 1;
                else right = middle;
            }

            int index = left - 1;
            pos += ivec2(size * text_advances_1[index], 0);
            result = uint(isText(screenTexel, pos, text_encodings_1[index], size)) * color;
        }
    }



	return result;
}

vec3 renderText_2(ivec2 pos, int size, vec3 color) {
	vec3 result = vec3(0.0);
    ivec2 screenTexel = ivec2(gl_FragCoord.st);

    if (max(screenTexel, ivec2(pos.x, pos.y - size * 6)) == screenTexel) {
        int lastText = text_advances_2[text_encodings_2.length() - 1];
        if (min(screenTexel, ivec2(pos.x + size * (lastText + 6), pos.y + size * 11)) == screenTexel) {
            int relPos = screenTexel.x - pos.x;
            relPos /= size;

            // Binary search for the character index
            int left = 0, right = text_advances_2.length();
            while (left < right) {
                int middle = (left + right) >> 1;
                if (relPos >= text_advances_2[middle]) left = middle + 1;
                else right = middle;
            }

            int index = left - 1;
            pos += ivec2(size * text_advances_2[index], 0);
            result = uint(isText(screenTexel, pos, text_encodings_2[index], size)) * color;
        }
    }



	return result;
}

//================================// Text Background Render //==================================//

//pos and size should be the same as the text
vec3 renderBackground_0(ivec2 pos, int size, vec3 color) {
    ivec2 texel = ivec2(gl_FragCoord.st);

    ivec2 start = pos - size;
    // Calculate the offset
    uint offsetX = text_advances_0[text_advances_0.length() - 1] * size + (size << 3);
    uint offsetY = size << 3 ;
    ivec2 end = pos + ivec2(offsetX, offsetY);

    if (texel == clamp(texel, start, end)) {
        return color;
    }
    return vec3(0.0);
}

vec3 renderBackground_1(ivec2 pos, int size, vec3 color) {
    ivec2 texel = ivec2(gl_FragCoord.st);

    ivec2 start = pos - size;
    // Calculate the offset
    uint offsetX = text_advances_1[text_advances_1.length() - 1] * size + (size << 3);
    uint offsetY = size << 3 ;
    ivec2 end = pos + ivec2(offsetX, offsetY);

    if (texel == clamp(texel, start, end)) {
        return color;
    }
    return vec3(0.0);
}

vec3 renderBackground_2(ivec2 pos, int size, vec3 color) {
    ivec2 texel = ivec2(gl_FragCoord.st);

    ivec2 start = pos - size;
    // Calculate the offset
    uint offsetX = text_advances_2[text_advances_2.length() - 1] * size + (size << 3);
    uint offsetY = size << 3 ;
    ivec2 end = pos + ivec2(offsetX, offsetY);

    if (texel == clamp(texel, start, end)) {
        return color;
    }
    return vec3(0.0);
}

vec3 renderBackground(ivec2 startPos, ivec2 endPos,vec3 color) {
    ivec2 texel = ivec2(gl_FragCoord.st);
    if (texel == clamp(texel, startPos, endPos)) {
        return color;
    }
    return vec3(0.0);
}

void renderBackground(in ivec2 startPos, in ivec2 endPos, inout vec3 originalColor, in vec3 color) {
    ivec2 texel = ivec2(gl_FragCoord.st);
    if (texel == clamp(texel, startPos, endPos)) {
        originalColor = color;
    }
}
//==================================// Number Render //==========================================//


const uvec3 number[]=
{
    CHAR_0,
    CHAR_1,
    CHAR_2,
    CHAR_3,
    CHAR_4,
    CHAR_5,
    CHAR_6,
    CHAR_7,
    CHAR_8,
    CHAR_9
};

const uvec3 signOfNumber[]=
{
    CHAR_DOT,
    CHAR_e,
    CHAR_MINUS,
};


// Original Text: Infinity
const uvec3 INF_encodings[] = {CHAR_I,CHAR_n,CHAR_f,CHAR_i,CHAR_n,CHAR_i,CHAR_t,CHAR_y,};
const int INF_advances[] = {0,4,10,15,17,23,25,29,};

vec3 outputINF(ivec2 pos, int size, vec3 color) {
	vec3 result = vec3(0.0);
    ivec2 screenTexel = ivec2(gl_FragCoord.s, gl_FragCoord.t - size);

    if (max(screenTexel, ivec2(pos.x, pos.y - size * 6)) == screenTexel) {
        int lastText = INF_advances[INF_encodings.length() - 1];
        if (min(screenTexel, ivec2(pos.x + size * (lastText + 6), pos.y + size * 11)) == screenTexel) {
            int relPos = screenTexel.x - pos.x;
            relPos /= size;

            // Binary search for the character index
            int left = 0, right = INF_advances.length();
            while (left < right) {
                int middle = (left + right) >> 1;
                if (relPos >= INF_advances[middle]) left = middle + 1;
                else right = middle;
            }

            int index = left - 1;
            pos += ivec2(size * INF_advances[index], 0);
            result = uint(isText(screenTexel, pos, INF_encodings[index], size)) * color;
        }
    }

	return result;
}


// Original Text: Not a Number
const uvec3 NAN_encodings[] = {CHAR_N,CHAR_o,CHAR_t,CHAR_SPACE,CHAR_a,CHAR_SPACE,CHAR_N,CHAR_u,CHAR_m,CHAR_b,CHAR_e,CHAR_r,};
const int NAN_advances[] = {0,6,12,16,22,28,34,40,46,52,58,64,};

vec3 outputNAN(ivec2 pos, int size, vec3 color) {
	vec3 result = vec3(0.0);
    ivec2 screenTexel = ivec2(gl_FragCoord.s,gl_FragCoord.t - size);

    if (max(screenTexel, ivec2(pos.x, pos.y - size * 6)) == screenTexel) {
        int lastText = NAN_advances[NAN_encodings.length() - 1];
        if (min(screenTexel, ivec2(pos.x + size * (lastText + 6), pos.y + size * 11)) == screenTexel) {
            int relPos = screenTexel.x - pos.x;
            relPos /= size;

            // Binary search for the character index
            int left = 0, right = NAN_advances.length();
            while (left < right) {
                int middle = (left + right) >> 1;
                if (relPos >= NAN_advances[middle]) left = middle + 1;
                else right = middle;
            }

            int index = left - 1;
            pos += ivec2(size * NAN_advances[index], 0);
            result = uint(isText(screenTexel, pos, NAN_encodings[index], size)) * color;
        }
    }

	return result;
}

// uint
vec3 outputNumber(uint num, ivec2 pos, int size, vec3 color){

    vec3 numColor = vec3(0.0);
    // special value
    if (isnan(num)) {
        return outputNAN(pos,size,vec3(1,0,0));
    }
    else if (isinf(num)) {
        return outputINF(pos,size,vec3(1,0,0));
    }

    ivec2 texel = ivec2(gl_FragCoord.st);
    ivec2 posOffset = ivec2(0, size);

    // Calculate the number of significant digits.
    uint numDigits = 1;
    uint tempNum = num;
    uint divisor = 1;

    while (tempNum / divisor >= 10) {
        divisor *= 10;
        numDigits++;
    }

    // If there isn't any significant digit,return 1 to display a "0"
    if (numDigits == 0) { numDigits = 1; }

    // Render the significant digit
    for (uint i = 0; i < numDigits; i++) {
        uint digit = (num / divisor) % 10;
        ivec2 digitPos = pos + posOffset + ivec2(i * size * 6, 0);

        if (max(texel, digitPos) == texel) {
            if (min(texel, digitPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, digitPos, number[digit], size));
            }
        }
        divisor /= 10;
    }

    return numColor;

}

bool isNegative(int num){
    if (num < 0) { return true; } else { return false; }
}

bool isNegative(float num){
    if (num < 0) { return true; } else { return false; }
}


float log10(float x) {
    return log2(x) / log2(10.0);
}

// int
vec3 outputNumber(int num, ivec2 pos, int size, vec3 color){

    vec3 numColor = vec3(0.0);
    // special value
    if (isnan(num)) {
        return outputNAN(pos,size,vec3(1,0,0));
    }
    else if (isinf(num)) {
        return outputINF(pos,size,vec3(1,0,0));
    }

    ivec2 texel = ivec2(gl_FragCoord.st);
    ivec2 posOffset = ivec2(0, size);

    // Calculate the number of significant digits.
    int numDigits = 1;
    int tempNum = abs(num);
    int divisor = 1;

    while (tempNum / divisor >= 10) {
        divisor *= 10;
        numDigits++;
    }

    // If there isn't any significant digit,return 1 to display a "0"
    if (numDigits == 0) { numDigits = 1; }

    // Render the significant digit
    for (int i = 0; i < numDigits; i++) {
        int digit = (abs(num) / divisor) % 10;
        ivec2 digitPos = pos + posOffset + ivec2(i * size * 6, 0);

        if (max(texel, digitPos) == texel) {
            if (min(texel, digitPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, digitPos, number[digit], size));
            }
        }
        divisor /= 10;
    }

    // Render negative sign
    ivec2 signPos = ivec2(pos.x - size * 6, pos.y + size * 2);
    if (max(texel, signPos) == texel) {
        if (min(texel, signPos + ivec2(size * 6, size * 11)) == texel) {
            numColor += color * uint(isText(texel, signPos, CHAR_MINUS, size)) * uint(isNegative(num));
        }
    }

    return numColor;

}

// Use less "while" to avoid TDR!
// float(The core of other types)
vec3 outputNumber(float num, ivec2 pos, int size, vec3 color) {
    vec3 numColor = vec3(0.0);

    // Special values
    if (isnan(num)) {
        return outputNAN(pos, size, vec3(1, 0, 0));
    } else if (isinf(num)) {
        return outputINF(pos, size, vec3(1, 0, 0));
    }

    ivec2 texel = ivec2(gl_FragCoord.st);
    ivec2 posOffset = ivec2(0, size);

    // Convert the number to scientific notation
    int exponent = 0;
    float normalizedNum = abs(num);

    // Normalize the number to be between 1 and 10
    if (normalizedNum > 0.0) {
        exponent = int(floor(log10(normalizedNum)));
        normalizedNum /= pow(10.0, float(exponent));
    } else {
        normalizedNum = 0.0;
    }

    // Round the normalized number to control precision
    normalizedNum = round(normalizedNum * 1e5) / 1e5; // Round to 5 decimal places

    // Render the mantissa (integer part and fractional part)
    int integerPart = int(normalizedNum);
    float fractionalPart = fract(normalizedNum);

    // Render the integer part
    int numDigits = 1;
    int tempNum = integerPart;
    int divisor = 1;

    while (tempNum / divisor >= 10) {
        divisor *= 10;
        numDigits++;
    }

    for (int i = 0; i < numDigits; i++) {
        int digit = (integerPart / divisor) % 10;
        ivec2 digitPos = pos + posOffset + ivec2(i * size * 6, 0);

        if (max(texel, digitPos) == texel) {
            if (min(texel, digitPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, digitPos, number[digit], size));
            }
        }
        divisor /= 10;
    }

    // Render the decimal point
    ivec2 decimalPos = pos + posOffset + ivec2(numDigits * size * 6, 0);
    if (max(texel, decimalPos) == texel) {
        if (min(texel, decimalPos + ivec2(size * 6, size * 11)) == texel) {
            numColor += color * uint(isText(texel, decimalPos, signOfNumber[0], size));
        }
    }

    // Render the fractional part (up to 5 digits)
    for (int i = 0; i < 5; i++) {
        fractionalPart *= 10.0;
        int digit = int(fractionalPart);
        fractionalPart -= float(digit);

        ivec2 digitPos = pos + posOffset + ivec2(size * ((numDigits + 1 + i) * 6 - 4), 0);

        if (max(texel, digitPos) == texel) {
            if (min(texel, digitPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, digitPos, number[digit], size));
            }
        }
    }

    // Render the 'e' for scientific notation
    ivec2 ePos = pos + posOffset + ivec2(size * ((numDigits + 6) *  6 - 4), 0);
    if (max(texel, ePos) == texel) {
        if (min(texel, ePos + ivec2(size * 6, size * 11)) == texel) {
            numColor += color * uint(isText(texel, ePos, signOfNumber[1], size));
        }
    }

    // Render the exponent
    int exponentDigits = 1;
    int tempExponent = abs(exponent);
    divisor = 1;

    while (tempExponent / divisor >= 10) {
        divisor *= 10;
        exponentDigits++;
    }

    int exponentRenderOffset = 0;

    // Render the negative sign for the exponent if necessary
    if (exponent < 0) {
        ivec2 signPos = pos + posOffset + ivec2(size * ((numDigits + 7) * 6 - 4), size);
        if (max(texel, signPos) == texel) {
            if (min(texel, signPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, signPos, signOfNumber[2], size));
            }
        }
        exponentRenderOffset += 1;
    }

    // Render the exponent
    for (int i = 0; i < exponentDigits; i++) {
        int digit = (abs(exponent) / divisor) % 10;

        ivec2 digitPos = pos + posOffset + ivec2(size * ((numDigits + 7 + i + exponentRenderOffset) * 6 - 4), 0);

        if (max(texel, digitPos) == texel) {
            if (min(texel, digitPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, digitPos, number[digit], size));
            }
        }
        divisor /= 10;
    }

    // Render negative sign
    ivec2 signPos = ivec2(pos.x - size * 6, pos.y + size * 2);
    if (max(texel, signPos) == texel) {
        if (min(texel, signPos + ivec2(size * 6, size * 11)) == texel) {
            numColor += color * uint(isText(texel, signPos, signOfNumber[2], size)) * uint(isNegative(num));
        }
    }

    return numColor;
}

//=================================// Function Graph Plotting //=================================//

// https://www.shadertoy.com/view/WslGzl
// Shader License: CC BY 3.0
// Author: Jan Mróz (jaszunio15)

// View setting
#define SCALE_X 8.0
#define SCALE_Y 4.5
#define CENTER_POINT vec2(0.0, 0.0)
#define THICKNESS 0.004

#define EPSILON 0.001
#define pow4(x) (x * x * x * x)

// Grid setting
#define GRID_THICKNESS 0.004
#define GRID1_DENSITY 1.0
#define GRID2_DENSITY 0.5
#define GRID_INTENSITY 0.2

// Define your function here:
float functionY(float x) { return ceil(sqrt(x) * 3); }

#define INITIALIZE_FUNCTION(f, color) funcData(f(uv.x), color , (f(uv.x + EPSILON) - f(uv.x - EPSILON)) / (2.0 * EPSILON), true)

struct funcData
{
 	float value;
    vec3 color;
    float derivative;
    bool inDomain;
};

// For grid calc
vec2 triangleFunc(vec2 x) { return (abs(fract(x) - 0.5)) * 2.0; }

void plotFunctionGraph(vec2 windowSize, inout vec3 color) {
    // uv = coordinate system
    vec2 uv = gl_FragCoord.xy * 2.0 / windowSize.xy;
    uv -= 1.0;
    uv *= vec2(SCALE_X, SCALE_Y);
    uv += CENTER_POINT;

    vec3 mainColor = vec3(0.0);

    // function and grid thickness
    float aspect = (windowSize.y / windowSize.x) / (SCALE_Y / SCALE_X);
    float hdScale = 1080.0 / windowSize.y;
    float thickness = THICKNESS * hdScale * min(SCALE_X, SCALE_Y);
    float gridThickness = GRID_THICKNESS * hdScale * min(SCALE_X, SCALE_Y);

    funcData func= INITIALIZE_FUNCTION(functionY, vec3(0.0, 1.0, 1.0));

    // vertical distance to function and dericative
    float distanceToFunction = abs(uv.y - func.value);
    float tgAlpha = clamp(abs(func.derivative * aspect), 0.0, 16.0); //clamp to avoid vertical lines (e.g. saw or square function)

    // vertical thickness from normal thickness and derivative
    float verticalThickness = sqrt(tgAlpha * tgAlpha + 3.0);
    float intensity = 1.0 - smoothstep(0.0, thickness, distanceToFunction / verticalThickness);
    if (func.inDomain) mainColor += func.color * pow4(intensity);

    //Adding grid
    vec2 grid;

    //OY and OX axis
    grid = smoothstep(vec2(1.0) - vec2(gridThickness * aspect, gridThickness), vec2(1.0), 1.0 - abs(uv));
    mainColor += vec3(max(grid.x, grid.y)) * GRID_INTENSITY * 0.5;

    //GRID1
    grid = smoothstep(vec2(1.0) - vec2(gridThickness * aspect, gridThickness) / GRID1_DENSITY, vec2(1.0), triangleFunc(uv / GRID1_DENSITY));
    mainColor += vec3(max(grid.x, grid.y)) * GRID_INTENSITY;
    //GRID2
    grid = smoothstep(vec2(1.0) - vec2(gridThickness * aspect, gridThickness) / GRID2_DENSITY, vec2(1.0), triangleFunc(uv / GRID2_DENSITY));
    mainColor += vec3(max(grid.x, grid.y)) * GRID_INTENSITY * 0.5;

    color = mainColor;

}

//================================// Matrix And Vector Render //=================================//


vec3 outputMatrix(mat2 mat, ivec2 pos, int size, vec3 color)
{

    vec3 matColor = vec3(0.0);
    ivec2 leftBracketPos = ivec2(pos.x, pos.y);
    ivec2 rightBracketPos = ivec2(pos.x + 112 * size, pos.y);

    /*

    // It's strange to have a huge rectangular bracket, isn't it?
    // LEFT_BRACKET
    if (max(texel, leftBracketPos) == texel) {
        if (min(texel, leftBracketPos + ivec2(size * 24, size * 44)) == texel) {
            matColor += color * uint(isText(texel, leftBracketPos, CHAR_LEFT_BRACKET, size*4));
        }
    }

    */

    matColor += outputNumber(mat[0][0], ivec2(pos.x + 8.33  * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][1], ivec2(pos.x + 83.33 * size,pos.y + 15.0 * size), size, color);

    matColor += outputNumber(mat[1][0], ivec2(pos.x + 8.33  * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][1], ivec2(pos.x + 83.33 * size,pos.y + 4.16 * size), size, color);

    /*

    // RIGHT_BRACKET
     if (max(texel, rightBracketPos) == texel) {
        if (min(texel,rightBracketPos + ivec2(size * 24, size * 44)) == texel) {
            matColor += color * uint(isText(texel, rightBracketPos, CHAR_RIGHT_BRACKET, size*4));
        }
    }

    */
    return matColor;
}

vec3 outputMatrix(mat2x3 mat, ivec2 pos, int size, vec3 color)
{

    vec3 matColor = vec3(0.0);

    matColor += outputNumber(mat[0][0], ivec2(pos.x + 8.33   * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][1], ivec2(pos.x + 83.33  * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][2], ivec2(pos.x + 158.33 * size,pos.y + 15.0 * size), size, color);

    matColor += outputNumber(mat[1][0], ivec2(pos.x + 8.33   * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][1], ivec2(pos.x + 83.33  * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][2], ivec2(pos.x + 158.33 * size,pos.y + 4.16 * size), size, color);

    return matColor;
}

vec3 outputMatrix(mat2x4 mat, ivec2 pos, int size, vec3 color)
{

    vec3 matColor = vec3(0.0);

    matColor += outputNumber(mat[0][0], ivec2(pos.x + 8.33   * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][1], ivec2(pos.x + 83.33  * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][2], ivec2(pos.x + 158.33 * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][3], ivec2(pos.x + 233.33 * size,pos.y + 15.0 * size), size, color);

    matColor += outputNumber(mat[1][0], ivec2(pos.x + 8.33   * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][1], ivec2(pos.x + 83.33  * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][2], ivec2(pos.x + 158.33 * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][3], ivec2(pos.x + 233.33 * size,pos.y + 4.16 * size), size, color);

    return matColor;
}



vec3 outputMatrix(mat3 mat, ivec2 pos, int size, vec3 color)
{

    vec3 matColor = vec3(0.0);

    matColor += outputNumber(mat[0][0], ivec2(pos.x + 8.33   * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][1], ivec2(pos.x + 83.33  * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][2], ivec2(pos.x + 158.33 * size,pos.y + 15.0 * size), size, color);

    matColor += outputNumber(mat[1][0], ivec2(pos.x + 8.33   * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][1], ivec2(pos.x + 83.33  * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][2], ivec2(pos.x + 158.33 * size,pos.y + 4.16 * size), size, color);

    matColor += outputNumber(mat[2][0], ivec2(pos.x + 8.33   * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][1], ivec2(pos.x + 83.33  * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][2], ivec2(pos.x + 158.33 * size,pos.y - 6.66 * size), size, color);

    return matColor;
}

vec3 outputMatrix(mat3x2 mat, ivec2 pos, int size, vec3 color)
{

    vec3 matColor = vec3(0.0);

    matColor += outputNumber(mat[0][0], ivec2(pos.x + 8.33   * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][1], ivec2(pos.x + 83.33  * size,pos.y + 15.0 * size), size, color);

    matColor += outputNumber(mat[1][0], ivec2(pos.x + 8.33   * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][1], ivec2(pos.x + 83.33  * size,pos.y + 4.16 * size), size, color);

    matColor += outputNumber(mat[2][0], ivec2(pos.x + 8.33   * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][1], ivec2(pos.x + 83.33  * size,pos.y - 6.66 * size), size, color);

    return matColor;
}

vec3 outputMatrix(mat3x4 mat, ivec2 pos, int size, vec3 color)
{

    vec3 matColor = vec3(0.0);
    matColor += outputNumber(mat[0][0], ivec2(pos.x + 8.33   * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][1], ivec2(pos.x + 83.33  * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][2], ivec2(pos.x + 158.33 * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][3], ivec2(pos.x + 233.33 * size,pos.y + 15.0 * size), size, color);

    matColor += outputNumber(mat[1][0], ivec2(pos.x + 8.33   * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][1], ivec2(pos.x + 83.33  * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][2], ivec2(pos.x + 158.33 * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][3], ivec2(pos.x + 233.33 * size,pos.y + 4.16 * size), size, color);

    matColor += outputNumber(mat[2][0], ivec2(pos.x + 8.33   * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][1], ivec2(pos.x + 83.33  * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][2], ivec2(pos.x + 158.33 * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][3], ivec2(pos.x + 233.33 * size,pos.y - 6.66 * size), size, color);

    return matColor;
}



vec3 outputMatrix(mat4 mat, ivec2 pos, int size, vec3 color)
{

    vec3 matColor = vec3(0.0);

    matColor += outputNumber(mat[0][0], ivec2(pos.x + 8.33   * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][1], ivec2(pos.x + 83.33  * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][2], ivec2(pos.x + 158.33 * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][3], ivec2(pos.x + 233.33 * size,pos.y + 15.0 * size), size, color);

    matColor += outputNumber(mat[1][0], ivec2(pos.x + 8.33   * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][1], ivec2(pos.x + 83.33  * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][2], ivec2(pos.x + 158.33 * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][3], ivec2(pos.x + 233.33 * size,pos.y + 4.16 * size), size, color);

    matColor += outputNumber(mat[2][0], ivec2(pos.x + 8.33   * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][1], ivec2(pos.x + 83.33  * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][2], ivec2(pos.x + 158.33 * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][3], ivec2(pos.x + 233.33 * size,pos.y - 6.66 * size), size, color);

    matColor += outputNumber(mat[3][0], ivec2(pos.x + 8.33   * size,pos.y - 17.5 * size), size, color);
    matColor += outputNumber(mat[3][1], ivec2(pos.x + 83.33  * size,pos.y - 17.5 * size), size, color);
    matColor += outputNumber(mat[3][2], ivec2(pos.x + 158.33 * size,pos.y - 17.5 * size), size, color);
    matColor += outputNumber(mat[3][3], ivec2(pos.x + 233.33 * size,pos.y - 17.5 * size), size, color);


    return matColor;
}

vec3 outputMatrix(mat4x2 mat, ivec2 pos, int size, vec3 color)
{

    vec3 matColor = vec3(0.0);

    matColor += outputNumber(mat[0][0], ivec2(pos.x + 8.33   * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][1], ivec2(pos.x + 83.33  * size,pos.y + 15.0 * size), size, color);

    matColor += outputNumber(mat[1][0], ivec2(pos.x + 8.33   * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][1], ivec2(pos.x + 83.33  * size,pos.y + 4.16 * size), size, color);

    matColor += outputNumber(mat[2][0], ivec2(pos.x + 8.33   * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][1], ivec2(pos.x + 83.33  * size,pos.y - 6.66 * size), size, color);

    matColor += outputNumber(mat[3][0], ivec2(pos.x + 8.33   * size,pos.y - 17.5 * size), size, color);
    matColor += outputNumber(mat[3][1], ivec2(pos.x + 83.33  * size,pos.y - 17.5 * size), size, color);

    return matColor;
}

vec3 outputMatrix(mat4x3 mat, ivec2 pos, int size, vec3 color)
{

    vec3 matColor = vec3(0.0);

    matColor += outputNumber(mat[0][0], ivec2(pos.x + 8.33   * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][1], ivec2(pos.x + 83.33  * size,pos.y + 15.0 * size), size, color);
    matColor += outputNumber(mat[0][2], ivec2(pos.x + 158.33 * size,pos.y + 15.0 * size), size, color);

    matColor += outputNumber(mat[1][0], ivec2(pos.x + 8.33   * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][1], ivec2(pos.x + 83.33  * size,pos.y + 4.16 * size), size, color);
    matColor += outputNumber(mat[1][2], ivec2(pos.x + 158.33 * size,pos.y + 4.16 * size), size, color);

    matColor += outputNumber(mat[2][0], ivec2(pos.x + 8.33   * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][1], ivec2(pos.x + 83.33  * size,pos.y - 6.66 * size), size, color);
    matColor += outputNumber(mat[2][2], ivec2(pos.x + 158.33 * size,pos.y - 6.66 * size), size, color);

    matColor += outputNumber(mat[3][0], ivec2(pos.x + 8.33   * size,pos.y - 17.5 * size), size, color);
    matColor += outputNumber(mat[3][1], ivec2(pos.x + 83.33  * size,pos.y - 17.5 * size), size, color);
    matColor += outputNumber(mat[3][2], ivec2(pos.x + 158.33 * size,pos.y - 17.5 * size), size, color);

    return matColor;
}



vec3 outputVector(vec2 vec, ivec2 pos, int size, vec3 color)
{

    vec3 vecColor = vec3(0.0);

    vecColor += outputNumber(vec.x, ivec2(pos.x + 8.33   * size,pos.y + 15.0     * size), size, color);
    vecColor += outputNumber(vec.y, ivec2(pos.x + 83.33  * size,pos.y + 15.0     * size), size, color);

    return vecColor;
}

vec3 outputVector(vec3 vec, ivec2 pos, int size, vec3 color)
{

    vec3 vecColor = vec3(0.0);

    vecColor += outputNumber(vec.x, ivec2(pos.x + 8.33   * size,pos.y + 15.0     * size), size, color);
    vecColor += outputNumber(vec.y, ivec2(pos.x + 83.33  * size,pos.y + 15.0     * size), size, color);
    vecColor += outputNumber(vec.z, ivec2(pos.x + 158.33 * size,pos.y + 15.0     * size), size, color);

    return vecColor;
}

vec3 outputVector(vec4 vec, ivec2 pos, int size, vec3 color)
{

    vec3 vecColor = vec3(0.0);

    vecColor += outputNumber(vec.x, ivec2(pos.x + 8.33   * size,pos.y + 15.0     * size), size, color);
    vecColor += outputNumber(vec.y, ivec2(pos.x + 83.33  * size,pos.y + 15.0     * size), size, color);
    vecColor += outputNumber(vec.z, ivec2(pos.x + 158.33 * size,pos.y + 15.0     * size), size, color);
    vecColor += outputNumber(vec.w, ivec2(pos.x + 233.33 * size,pos.y + 15.0     * size), size, color);

    return vecColor;
}

//=========================================// Others //==========================================//

// Original Text: True
const uvec3 TRUE_encodings[] = {CHAR_T,CHAR_r,CHAR_u,CHAR_e,};
const int TRUE_advances[] = {0,6,12,18,};

vec3 outputTrue(ivec2 pos, int size, vec3 color) {
	vec3 result = vec3(0.0);
    ivec2 screenTexel = ivec2(gl_FragCoord.s, gl_FragCoord.t - size);

    if (max(screenTexel, ivec2(pos.x, pos.y - size * 6)) == screenTexel) {
        int lastText = TRUE_advances[TRUE_encodings.length() - 1];
        if (min(screenTexel, ivec2(pos.x + size * (lastText + 6), pos.y + size * 11)) == screenTexel) {
            int relPos = screenTexel.x - pos.x;
            relPos /= size;

            // Binary search for the character index
            int left = 0, right = TRUE_advances.length();
            while (left < right) {
                int middle = (left + right) >> 1;
                if (relPos >= TRUE_advances[middle]) left = middle + 1;
                else right = middle;
            }

            int index = left - 1;
            pos += ivec2(size * TRUE_advances[index], 0);
            result = uint(isText(screenTexel, pos, TRUE_encodings[index], size)) * color;
        }
    }

	return result;
}

// Original Text: False
const uvec3 FALSE_encodings[] = {CHAR_F,CHAR_a,CHAR_l,CHAR_s,CHAR_e,};
const int FALSE_advances[] = {0,6,12,15,21,};

vec3 outputFalse(ivec2 pos, int size, vec3 color) {
	vec3 result = vec3(0.0);
    ivec2 screenTexel = ivec2(gl_FragCoord.s,gl_FragCoord.t - size);

    if (max(screenTexel, ivec2(pos.x, pos.y - size * 6)) == screenTexel) {
        int lastText = FALSE_advances[FALSE_encodings.length() - 1];
        if (min(screenTexel, ivec2(pos.x + size * (lastText + 6), pos.y + size * 11)) == screenTexel) {
            int relPos = screenTexel.x - pos.x;
            relPos /= size;

            // Binary search for the character index
            int left = 0, right = FALSE_advances.length();
            while (left < right) {
                int middle = (left + right) >> 1;
                if (relPos >= FALSE_advances[middle]) left = middle + 1;
                else right = middle;
            }

            int index = left - 1;
            pos += ivec2(size * FALSE_advances[index], 0);
            result = uint(isText(screenTexel, pos, FALSE_encodings[index], size)) * color;
        }
    }

	return result;
}

vec3 outputBool(bool b, ivec2 pos, int size, vec3 color) {

    vec3 result = vec3(0.0);

    if (b) {
        result = outputTrue(pos, size, color);
    } else {
        result = outputFalse(pos, size, color);
    }

    return result;
}

void outputColor(inout vec3 inputOutputCol, vec3 outputCol, ivec2 pos, int size) {

    ivec2 screenTexel = ivec2(gl_FragCoord.s, gl_FragCoord.t - size);
        if (max(screenTexel, ivec2(pos.x, pos.y - size * 6)) == screenTexel) {
            if (min(screenTexel, ivec2(pos.x + size *  6, pos.y)) == screenTexel) {
               inputOutputCol = outputCol;
        }
    }

}

/*

These seemingly redundant functions are for my own debugging convenience,
and they can be completely deleted if you don't like them.

*/

void outputBufferData(inout vec3 inputOutputCol, sampler2D tex)
{
    inputOutputCol = texelFetch(tex,ivec2(gl_FragCoord.xy), 0).rgb;
}

void outputBufferData(inout vec3 inputOutputCol, vec2 screenCoord, sampler2D tex0, sampler2D tex1, sampler2D tex2, sampler2D tex3)
{

    if (screenCoord.x < 0.5 && screenCoord.y > 0.5) {
        inputOutputCol = texture(tex0,vec2(screenCoord.x, screenCoord.y - 0.5) * 2.0).rgb;
    } else if (screenCoord.x > 0.5 && screenCoord.y > 0.5) {
        inputOutputCol = texture(tex1,vec2(screenCoord.x - 0.5, screenCoord.y - 0.5) * 2.0).rgb;
    } else if (screenCoord.x < 0.5 && screenCoord.y < 0.5) {
        inputOutputCol = texture(tex2,vec2(screenCoord.x, screenCoord.y) * 2.0).rgb;
    } else {
        inputOutputCol = texture(tex3,vec2(screenCoord.x - 0.5, screenCoord.y) * 2.0).rgb;
    }

}

// This function wasn't efficient and it was abandoned.

/*

// float(with accuracy)
vec3 outputNumber(float num, ivec2 pos, int size, vec3 color, uint accuracy) {

    vec3 numColor = vec3(0.0);

    // Special values
    if (isnan(num)) {
        return outputNAN(pos, size, vec3(1, 0, 0));
    } else if (isinf(num)) {
        return outputINF(pos, size, vec3(1, 0, 0));
    }


    ivec2 texel = ivec2(gl_FragCoord.st);
    ivec2 posOffset = ivec2(0, size);

    // Convert the number to scientific notation
    int exponent = 0;
    float absNum = abs(num);

    // Normalize the number to be between 1 and 10
    while (absNum >= 10.0) {
        absNum /= 10.0;
        exponent++;
    }
    while (absNum < 1.0) {
        absNum *= 10.0;
        exponent--;
    }

    // Render the mantissa (integer part and fractional part)
    int integerPart = int(absNum);
    float fractionalPart = fract(absNum);


    // Render the integer part
    int numDigits = 1;
    int tempNum = integerPart;
    int divisor = 1;

    while (tempNum / divisor >= 10) {
        divisor *= 10;
        numDigits++;
    }

    for (int i = 0; i < numDigits; i++) {
        int digit = (integerPart / divisor) % 10;
        ivec2 digitPos = pos + posOffset + ivec2(i * size * 6, 0);

        if (max(texel, digitPos) == texel) {
            if (min(texel, digitPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, digitPos, number[digit], size));
            }
        }
        divisor /= 10;
    }

    // Render the decimal point
    ivec2 decimalPos = pos + posOffset + ivec2(numDigits * size * 6, 0);
    if (max(texel, decimalPos) == texel) {
        if (min(texel, decimalPos + ivec2(size * 6, size * 11)) == texel) {
            numColor += color * uint(isText(texel, decimalPos, signOfNumber[0], size));
        }
    }

    // Render the fractional part
    for (int i = 0; i < accuracy; i++) {
        fractionalPart *= 10.0;
        int digit = int(fractionalPart);
        fractionalPart -= float(digit);

        ivec2 digitPos = pos + posOffset + ivec2(size * ((numDigits + 1 + i) * 6 - 4), 0);

        if (max(texel, digitPos) == texel) {
            if (min(texel, digitPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, digitPos, number[digit], size));
            }
        }
    }

    // Render the 'e' for scientific notation
    ivec2 ePos = pos + posOffset + ivec2(size * ((numDigits + 1 + accuracy) * 6 - 4), 0);
    if (max(texel, ePos) == texel) {
        if (min(texel, ePos + ivec2(size * 6, size * 11)) == texel) {
            numColor += color * uint(isText(texel, ePos, signOfNumber[1], size));
        }
    }

    int exponentDigits = 1;
    int tempExponent = abs(exponent);
    divisor = 1;

    while (tempExponent / divisor >= 10) {
        divisor *= 10;
        exponentDigits++;
    }

    // This offset is used to bring the index closer to "e" when there is no sign before the index
    int exponentRenderOffset = 0;

    // Render the negative sign for the exponent if necessary
    if (exponent < 0) {
        ivec2 signPos = pos + posOffset + ivec2(size * ((numDigits + 1 + accuracy + exponentDigits) * 6 - 4), 0);
        if (max(texel, signPos) == texel) {
            if (min(texel, signPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, signPos, signOfNumber[2], size));
            }
        }
    }
    else{
        exponentRenderOffset += 1;
    }

    // Render the exponent
    for (int i = 0; i < exponentDigits; i++) {
        int digit = (abs(exponent) / divisor) % 10;

        ivec2 digitPos = pos + posOffset + ivec2(size * ((numDigits + 3 + accuracy + i - exponentRenderOffset) * 6 - 4), 0);

        if (max(texel, digitPos) == texel) {
            if (min(texel, digitPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, digitPos, number[digit], size));
            }
        }
        divisor /= 10;
    }

    // Render negative sign
    ivec2 signPos = ivec2(pos.x - size * 6, pos.y + size * 2);
        if (max(texel, signPos) == texel) {
            if (min(texel, signPos + ivec2(size * 6, size * 11)) == texel) {
                numColor += color * uint(isText(texel, signPos, signOfNumber[2], size)) * uint(isNegative(num));
            }
        }


    return numColor;
}

*/
